// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//同步客户端玩家ID
type SyncPID struct {
	PID                  int32    `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPID) Reset()         { *m = SyncPID{} }
func (m *SyncPID) String() string { return proto.CompactTextString(m) }
func (*SyncPID) ProtoMessage()    {}
func (*SyncPID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *SyncPID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPID.Unmarshal(m, b)
}
func (m *SyncPID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPID.Marshal(b, m, deterministic)
}
func (m *SyncPID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPID.Merge(m, src)
}
func (m *SyncPID) XXX_Size() int {
	return xxx_messageInfo_SyncPID.Size(m)
}
func (m *SyncPID) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPID.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPID proto.InternalMessageInfo

func (m *SyncPID) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

//玩家位置
type Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	V                    float32  `protobuf:"fixed32,4,opt,name=V,proto3" json:"V,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

//玩家广播数据
type BroadCast struct {
	PID int32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Tp  int32 `protobuf:"varint,2,opt,name=Tp,proto3" json:"Tp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCast_Content
	//	*BroadCast_P
	//	*BroadCast_ActionData
	Data                 isBroadCast_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadCast) Reset()         { *m = BroadCast{} }
func (m *BroadCast) String() string { return proto.CompactTextString(m) }
func (*BroadCast) ProtoMessage()    {}
func (*BroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *BroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCast.Unmarshal(m, b)
}
func (m *BroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCast.Marshal(b, m, deterministic)
}
func (m *BroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCast.Merge(m, src)
}
func (m *BroadCast) XXX_Size() int {
	return xxx_messageInfo_BroadCast.Size(m)
}
func (m *BroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCast proto.InternalMessageInfo

func (m *BroadCast) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *BroadCast) GetTp() int32 {
	if m != nil {
		return m.Tp
	}
	return 0
}

type isBroadCast_Data interface {
	isBroadCast_Data()
}

type BroadCast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,proto3,oneof"`
}

type BroadCast_P struct {
	P *Position `protobuf:"bytes,4,opt,name=P,proto3,oneof"`
}

type BroadCast_ActionData struct {
	ActionData int32 `protobuf:"varint,5,opt,name=ActionData,proto3,oneof"`
}

func (*BroadCast_Content) isBroadCast_Data() {}

func (*BroadCast_P) isBroadCast_Data() {}

func (*BroadCast_ActionData) isBroadCast_Data() {}

func (m *BroadCast) GetData() isBroadCast_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCast) GetContent() string {
	if x, ok := m.GetData().(*BroadCast_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCast) GetP() *Position {
	if x, ok := m.GetData().(*BroadCast_P); ok {
		return x.P
	}
	return nil
}

func (m *BroadCast) GetActionData() int32 {
	if x, ok := m.GetData().(*BroadCast_ActionData); ok {
		return x.ActionData
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BroadCast) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BroadCast_Content)(nil),
		(*BroadCast_P)(nil),
		(*BroadCast_ActionData)(nil),
	}
}

//玩家聊天数据
type Talk struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talk) Reset()         { *m = Talk{} }
func (m *Talk) String() string { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()    {}
func (*Talk) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Talk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talk.Unmarshal(m, b)
}
func (m *Talk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talk.Marshal(b, m, deterministic)
}
func (m *Talk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talk.Merge(m, src)
}
func (m *Talk) XXX_Size() int {
	return xxx_messageInfo_Talk.Size(m)
}
func (m *Talk) XXX_DiscardUnknown() {
	xxx_messageInfo_Talk.DiscardUnknown(m)
}

var xxx_messageInfo_Talk proto.InternalMessageInfo

func (m *Talk) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//玩家信息
type Player struct {
	PID                  int32     `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	P                    *Position `protobuf:"bytes,2,opt,name=P,proto3" json:"P,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *Player) GetP() *Position {
	if m != nil {
		return m.P
	}
	return nil
}

//同步玩家显示数据
type SyncPlayers struct {
	Ps                   []*Player `protobuf:"bytes,1,rep,name=ps,proto3" json:"ps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SyncPlayers) Reset()         { *m = SyncPlayers{} }
func (m *SyncPlayers) String() string { return proto.CompactTextString(m) }
func (*SyncPlayers) ProtoMessage()    {}
func (*SyncPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *SyncPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPlayers.Unmarshal(m, b)
}
func (m *SyncPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPlayers.Marshal(b, m, deterministic)
}
func (m *SyncPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPlayers.Merge(m, src)
}
func (m *SyncPlayers) XXX_Size() int {
	return xxx_messageInfo_SyncPlayers.Size(m)
}
func (m *SyncPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPlayers proto.InternalMessageInfo

func (m *SyncPlayers) GetPs() []*Player {
	if m != nil {
		return m.Ps
	}
	return nil
}

//玩家猜数字
type Guess struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guess) Reset()         { *m = Guess{} }
func (m *Guess) String() string { return proto.CompactTextString(m) }
func (*Guess) ProtoMessage()    {}
func (*Guess) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Guess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guess.Unmarshal(m, b)
}
func (m *Guess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guess.Marshal(b, m, deterministic)
}
func (m *Guess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guess.Merge(m, src)
}
func (m *Guess) XXX_Size() int {
	return xxx_messageInfo_Guess.Size(m)
}
func (m *Guess) XXX_DiscardUnknown() {
	xxx_messageInfo_Guess.DiscardUnknown(m)
}

var xxx_messageInfo_Guess proto.InternalMessageInfo

func (m *Guess) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncPID)(nil), "api.SyncPID")
	proto.RegisterType((*Position)(nil), "api.Position")
	proto.RegisterType((*BroadCast)(nil), "api.BroadCast")
	proto.RegisterType((*Talk)(nil), "api.Talk")
	proto.RegisterType((*Player)(nil), "api.Player")
	proto.RegisterType((*SyncPlayers)(nil), "api.SyncPlayers")
	proto.RegisterType((*Guess)(nil), "api.Guess")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0x6b, 0xa7, 0x69, 0x6f, 0x4e, 0x7a, 0x11, 0xf2, 0x64, 0x51, 0x21, 0x05, 0x4f, 0x15,
	0x43, 0x86, 0x32, 0x30, 0x30, 0x91, 0x46, 0x22, 0xdd, 0x2c, 0x13, 0x55, 0x6d, 0x36, 0xb7, 0x44,
	0x28, 0xa2, 0xc4, 0x56, 0x6c, 0x86, 0xbe, 0x06, 0x8f, 0xc1, 0x53, 0x22, 0x3b, 0x2a, 0x20, 0x51,
	0x26, 0xfb, 0x3b, 0xc7, 0xfe, 0xcf, 0x27, 0x1b, 0xa2, 0x57, 0xf3, 0x9c, 0xea, 0x4e, 0x59, 0x45,
	0x02, 0xa9, 0x1b, 0x36, 0x85, 0xf1, 0xe3, 0xa1, 0xdd, 0xf1, 0x65, 0x4e, 0xce, 0x21, 0xe0, 0xcb,
	0x9c, 0xa2, 0x04, 0xcd, 0x42, 0xe1, 0xb6, 0x2c, 0x83, 0x7f, 0x5c, 0x99, 0xc6, 0x36, 0xaa, 0x25,
	0x13, 0x40, 0x6b, 0xdf, 0xc3, 0x02, 0xad, 0x1d, 0x6d, 0x28, 0xee, 0x69, 0xe3, 0xa8, 0xa2, 0x41,
	0x4f, 0x95, 0xa3, 0x15, 0x1d, 0xf6, 0xb4, 0x62, 0xef, 0x08, 0xa2, 0xac, 0x53, 0xf2, 0x69, 0x21,
	0x8d, 0xfd, 0x3d, 0x83, 0x9c, 0x01, 0x2e, 0xb5, 0x8f, 0x0a, 0x05, 0x2e, 0x35, 0xb9, 0x80, 0xf1,
	0x42, 0xb5, 0xb6, 0x6e, 0xad, 0x4f, 0x8c, 0x8a, 0x81, 0x38, 0x16, 0xc8, 0x25, 0x20, 0xee, 0x93,
	0xe3, 0xf9, 0xff, 0x54, 0xea, 0x26, 0x3d, 0xda, 0x15, 0x03, 0x81, 0x38, 0x49, 0x00, 0xee, 0x77,
	0x0e, 0x73, 0x69, 0x25, 0x0d, 0x5d, 0x64, 0x31, 0x10, 0x3f, 0x6a, 0xd9, 0x08, 0x86, 0x6e, 0x65,
	0x09, 0x0c, 0x4b, 0xb9, 0x7f, 0x21, 0xf4, 0x7b, 0x98, 0x53, 0x8a, 0xbe, 0x46, 0xb1, 0x5b, 0x18,
	0xf1, 0xbd, 0x3c, 0xd4, 0xdd, 0x09, 0xe5, 0xa9, 0xd3, 0xc0, 0x27, 0x34, 0x04, 0xe2, 0xec, 0x1a,
	0x62, 0xff, 0xa0, 0xfe, 0xb2, 0x21, 0x53, 0xc0, 0xda, 0x50, 0x94, 0x04, 0xb3, 0x78, 0x1e, 0xf7,
	0x87, 0x7d, 0x47, 0x60, 0x6d, 0xd8, 0x15, 0x84, 0x0f, 0x6f, 0xb5, 0x31, 0x7f, 0x7b, 0x64, 0x93,
	0x2a, 0x4c, 0xef, 0xa4, 0x6e, 0x3e, 0x30, 0xe6, 0xdb, 0xed, 0xc8, 0xff, 0xdc, 0xcd, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0x1f, 0x7e, 0xad, 0xc6, 0x01, 0x00, 0x00,
}
